### ISSUE TITLE
Publishing to npm

### ISSUE THREAD

**Issue by kevinjonesevans** [dynamicflow/hapi-cognito#2]
Thanks for accepting my pr last night! If you could publish the change to npm sometime soon I would appreciate it!

**Comment by aro1976** [comment]
I already published the 2 pull requests (version 1.1.0), if you create an user on npmjs.com I would list you as a contributor there.

Best Regards,
Alessandro

**Comment by kevinjonesevans** [comment]
Created an account - my username is [ktje](https://www.npmjs.com/~ktje)
Thank you!
